# postgrest.conf
# PostgREST configuration file
# https://postgrest.org/en/stable/references/configuration.html

db-uri         = "postgres://pnp_bqt_reader:password@localhost:5432/bouquetin"
db-schemas     = "bouquetin"
db-anon-role   = "pnp_bqt_reader"
server-port    = 3000
